config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :days do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy]
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :days, through: :bookings
  has_many :bookings, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :day
  belongs_to :activity
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :activities, through: :bookings
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @day = Day.find(params[:day_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(bookingparams)
    @day = Day.find(params[:day_id])
    @booking.day = @day
    if @booking.save
      redirect_to day_path(@day)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to day_path(@booking.day)
  end

  private
  def bookingparams
    params.require(:booking).permit(:duration, :activity_id)
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index
    @days = Day.geocoded

    @markers = @days.map do |day|
      {
        lat: day.latitude,
        lng: day.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { day: day })
      }
    end
    @days = Day.all.order("date DESC")
  end

  def show
    @day = Day.find(params[:id])
    @bookings = @day.bookings
  end

  def new
    @day = Day.new
  end

  def create
    @day = Day.create(day_params)
    if @day.save
      redirect_to day_path(@day)
    else
      render :new
    end
  end

  def edit
    @day = Day.find(params[:id])
  end

  def update
    @day = Day.find(params[:id])
    @day.update(day_params)
    if @day.save
      redirect_to days_path
    else
      render :new
    end
  end

  def destroy
    @day = Day.find(params[:id])
    @day.destroy
    redirect_to days_path
  end

  private

  def day_params
    params.require(:day).permit(:date, :title, :address, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @disable_nav = true
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/new.html.erb
 <div class="container">
  <div class="row">
    <div class="col-md-4 mx-auto">
      <%= simple_form_for [ @day, @booking ] do |f| %>
        <%= f.association :activity, input_html: { class: "beautiful-dropdown" } %>
        <%= f.input :notes %>
        <%= f.input :duration %>
        <%= f.submit "Submit", class: "btn-pink" %>
      <% end %>
       <%= link_to "Back", day_path(@day), class: "btn-ghost-gray" %>
    </div>
  </div>
</div>

app/views/days/_info_window.html.erb
<h2><%= day.title %></h2>
<p><%= day.address %></p>

app/views/days/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>Modify the magic day</h1>
      <%= simple_form_for(@day) do |f| %>
        <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :title %>
        <%= f.input :address %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.button :submit, class: "btn-pink" %>
      <% end %>
      <%= link_to "Back", days_path, class: "btn-ghost-gray" %>
    </div>
  </div>
</div>

app/views/days/index.html.erb
<div class="whole"><%= link_to '<i class="fas fa-plus-circle"></i>'.html_safe, new_day_path, class: "plus" %>
  <div class="items">
    <div class="index">
      <% @days.each do |day| %>
       <div class="card"> <%= link_to day_path(day) do %>
          <div class="first_line">
            <p class="indextext">
              <%= day.title %> -
              <%= day.address %></p>
             <p class="date"><%= day.date %></p>
            <%= link_to '<i class="fas fa-times"></i>'.html_safe, day_path(day), method: :delete, data: {confirm: "Are you sure?"}, class: "x" %> </div>
          <% Booking.joins(:day).where(day: @day).each do |booking| %>
          <p> <%= booking.activity.name %></p>
          <% end %>
          <div> <%= link_to "Edit", edit_day_path(day), class: "btn-pink" %>
          </div>
        <% end %></div>
      <% end %>
    </div>

    <div>
      <div class="activities">
        <img src="https://images.unsplash.com/photo-1506126613408-eca07ce68773?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=862&q=80" style="width: 120px; height: 120px;" class="pic">
          <img src="https://images.unsplash.com/photo-1568480289356-5a75d0fd47fc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" style="width: 120px; height: 120px;" class="pic">
        <img src="https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" style="width: 120px; height: 120px;" class="pic">
          <img src="https://images.unsplash.com/photo-1515879218367-8466d910aaa4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" style="width: 120px; height: 120px;" class="pic">
        <img src="https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" style="width: 120px; height: 120px;" class="pic">
          <img src="https://images.unsplash.com/photo-1527058054345-f870ffe763eb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1351&q=80" style="width: 120px; height: 120px;" class="pic">
        <img src="https://images.unsplash.com/photo-1518609878373-06d740f60d8b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" style="width: 120px; height: 120px;" class="pic">
          <img src="https://images.unsplash.com/photo-1495837174058-628aafc7d610?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" style="width: 120px; height: 120px;" class="pic">
      </div>
        <div class="weather">
        <form action="" id="location" style="width:220px; margin:0 auto;">
          <h5>Get Today's Weather</h5>
          <input type="text" name="content" id="city" class="form-control" placeholder="Type the city..">
          <input type="submit" value="Send" class="btn-pink my-1">
        </form>
        <div class="weather-info" style="width:220px; margin:0 auto;">
          <div>
            <h1 id="header1"> </h1>
            <h4 id="header4"></h4>
            <p id="parag"></p>
            <p id="feelslike"></p>
          </div>
          <div>
            <img id='image'>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/days/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>A new magic day</h1>
      <%= simple_form_for(@day) do |f| %>
        <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :title %>
        <%= f.input :address %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.button :submit, class: "btn-pink" %>
      <% end %>
      <%= link_to "Back", days_path, class: "btn-ghost-gray" %>
    </div>
  </div>
</div>

app/views/days/show.html.erb
<div class="container px-0 my-3">
  <h3><strong> <%= @day.title %></strong></h3>
  <h5>(<%= @day.date %>)</h6>
  <br>
  <h4><strong>List the cool things you have done</strong> </h4>
    <% @bookings.each do |booking| %>
      <div class="row border mx-1 my-3 py-2 px-2">
        <div class= "col-4">
          <p><%= booking.activity.name %> - <%= booking.duration %> <%= booking.notes %> <%= link_to '<i class="fas fa-times"></i>'.html_safe, booking_path(booking), method: :delete, class: "x mx-4" %></p>
        </div>
      </div>
         <% end %>
    <% @day.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>

  <div class= "my-4">
    <%= link_to "Activity", new_day_booking_path(@day), class: "btn-pink" %>
    <%= link_to "Back", days_path, class: "btn-ghost-gray" %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Performance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Karla|Rubik:400,700&display=swap" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' unless @disable_nav %>
      <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="homepage" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),url(https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80);">
  <div class="container">
    <h1>How do you spend your days?</h1>
    <%= link_to "See More", days_path(@days), class: "btn btn-ghost" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="fixed-top navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "appicon.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Days", days_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/shared/navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>